x = input('Digite algo:')
print('Abaixo estará listado as informações da variável fornecida:')
print(f'O tipo primitivo é:    {type(x)}')
print(f'Só tem espaços?        {x.isspace()}')
print(f'É um número?           {x.isnumeric()}')
print(f'É alfabético?          {x.isalpha()}')
print(f'É um número?           {x.isnumeric()}')
print(f'É alfanumérico?        {x.isalnum()}')
print(f'Está em maiúsculas?    {x.isupper()}')
print(f'Está em minúsculas?    {x.islower()}')
print(f'Está capitalizada?     {x.istitle()}')
print(f'É uma letra?           {x.isalpha()}')
print(f'É decimal?             {x.isdecimal()}')

